version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - .:./
    environment:
      NODE_ENV: development
      DATABASE_URI: mongodb://mongo:27017/gateway_db
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - .:./
    depends_on:
      - backend
  mongo:
    image: mongo:5.0.5
    ports:
      - "27017:27017"
